# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/analyzer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/analyzer.proto\x12\x08\x61nalyzer\"S\n\x0c\x45mailRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x14\n\x0ctext_content\x18\x03 \x01(\t\x12\x0c\n\x04urls\x18\x04 \x03(\t\"\x9a\x01\n\x0f\x41nalyzeResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x13\n\x0bscore_level\x18\x02 \x01(\t\x12\x15\n\rnumeric_score\x18\x03 \x01(\x05\x12\x15\n\rjustification\x18\x04 \x01(\t\x12\x18\n\x10\x65xplanation_json\x18\x05 \x01(\t\x12\x18\n\x10\x65xplanation_text\x18\x06 \x01(\t2T\n\x0f\x41nalysisService\x12\x41\n\x0c\x41nalyzeEmail\x12\x16.analyzer.EmailRequest\x1a\x19.analyzer.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILREQUEST']._serialized_start=35
  _globals['_EMAILREQUEST']._serialized_end=118
  _globals['_ANALYZERESPONSE']._serialized_start=121
  _globals['_ANALYZERESPONSE']._serialized_end=275
  _globals['_ANALYSISSERVICE']._serialized_start=277
  _globals['_ANALYSISSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
